"""Centralized default configuration."""

from .defaults import (
    ANGLE_SIMILARITY_WEIGHT,
    DEFAULT_COUNTDOWN_LABELS,
    DEFAULT_SESSION_CONFIG,
    FEEDBACK_INTERVAL_MS,
    LANDMARK_DISTANCE_THRESHOLD,
    LANDMARK_SIMILARITY_WEIGHT,
    SLIDING_WINDOW_MS,
    TIMESTAMP_TOLERANCE_MS,
)

__all__ = [
    "ANGLE_SIMILARITY_WEIGHT",
    "DEFAULT_COUNTDOWN_LABELS",
    "DEFAULT_SESSION_CONFIG",
    "FEEDBACK_INTERVAL_MS",
    "LANDMARK_DISTANCE_THRESHOLD",
    "LANDMARK_SIMILARITY_WEIGHT",
    "SLIDING_WINDOW_MS",
    "TIMESTAMP_TOLERANCE_MS",
]
